linux-system-roles/timesync

tasks/main.yml, vars/main.yml
Users now can set the ntp_provider variable. If they don't, the default remains
as before.
https://bugzilla.redhat.com/show_bug.cgi?id=1597693
=> Make the provider configurable.

tasks/main.yml, vars/main.yml
for consistency with network, see https://github.com/linux-system-roles/network/issues/71
=> Rename timesync_ntp_provider_default to timesync_ntp_provider_os_default

templates/chrony.conf.j2, templates/ntp.conf.j2, templates/timemaster.conf.j2, vars/main.yml
Using tests as filters is deprecated and `version_compare` was renamed
to `version` in Ansible 2.5.
=> Use `is version` instead of `|version_compare`

handlers/main.yml, tasks/main.yml
Convert old ansible syntax to yaml. Old syntax is valid but it doesn't work great with code linters. Additionally everywhere in official ansible docs YAML format is used.
This PR doesn't change any functionalities as it only changes syntax.
Notice changes from `yes` to `true`. This was discovered by yamllint just because it was able to analyse parts which it couldn't with old syntax.
=> use yaml syntax

meta/main.yml
Fixes indentation in role's metadata:
--> Executing Yamllint on files found in timesync/...
timesync/meta/main.yml
9:3       error    wrong indentation: expected 4 but found 2  (indentation)
=> Fix yamllint error

defaults/main.yml, tasks/main.yml
Set the variable in defaults/main.yml to an empty string, so all input variables of the role are included there.
This PR includes #14 to avoid merge conflicts.
=>  Add empty timesync_ntp_provider to defaults 

tasks/main.yml
Force the command tasks to run in normal mode in order to allow the role
to run in check mode.
Also, change "False" to "no" for consistency.
Fixes #27.
=> Fix role to work in check mode

tasks/main.yml, tasks/setup/CentOS_6.yml, tasks/setup/RedHat_6.yml, tasks/setup/default.yml
Currently, we have errors, like these during execution role:
```
TASK [timesync : Disable ntpd] *************************************************************************************************************************************************************
fatal: [host1]: FAILED! => changed=false 
msg: 'Could not find the requested service ntpd: host'
...ignoring
fatal: [host2]: FAILED! => changed=false 
msg: 'Could not find the requested service ntpd: host'
...ignoring
TASK [timesync : Disable ntpdate] **********************************************************************************************************************************************************
fatal: [host1]: FAILED! => changed=false 
msg: 'Could not find the requested service ntpdate: host'
...ignoring
fatal: [host2]: FAILED! => …
```
=> Remove ignore_errors for Disable services tasks

tox.ini
This should fix this problem:
```
TASK [linux-system-roles.timesync : Set variable `timesync_services` with filtered uniq service names] ***
fatal: [centos-6]: FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}
fatal: [centos-7]: FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}
```
reported in https://github.com/linux-system-roles/timesync/pull/89#issuecomment-712104529
=> add jmespath as dependency for molecule

README.md, defaults/main.yml, templates/chrony.conf.j2, templates/ntp.conf.j2
This PR adds the ability to configure the Max Distance parameter for Chrony and NTP. This will allow, among others, to sync Linux clients to a Windows NTP server.
=> Add option to configure max distance 

vars/main.yml
Don't convert the version of chrony and ntp to int to not lose the
minor number after the dot.
=> Fix package versions

templates/chrony.conf.j2, vars/CentOS_6.yml, vars/CentOS_9.yml, vars/Fedora_33.yml, vars/RedHat_6.yml, vars/RedHat_9.yml, vars/default.yml
The chrony package in Fedora 33 changed configuration of NTP servers
from DHCP. Instead of relaying on a separate helper script, the sources
are now loaded directly from /run/chrony-dhcp.
This depends on #87.
=> Support chrony configuration in Fedora 33

README.md, defaults/main.yml, templates/chrony.conf.j2, tests/tests_ntp.yml
This PR adds options to enable NTP HW timestamping on specified interfaces, enable the interleaved mode and sample filtering in order to enable highly accurate and stable synchronization in local network.
=> Add support for HW timestamping with NTP

.github/workflows/tox.yml, .sanity-ansible-ignore-2.10.txt
- Add .sanity-ansible-ignore-2.10.txt
- Use tox-lsr 2.3.0 and enable ansible-test
=> RHELPLAN-68118 - Collections - Timesync - fixing ansible-test errors

.ansible-lint, tasks/main.yml, tests/tests_default_wrapper.yml, tests/tests_ntp_provider6.yml
- '301'  # Commands should not change things if nothing needs doing
- '305'  # Use shell only when shell functionality is required
=> Cleaning up ansible-lint errors except 301 and 303.

README.md, templates/ptp4l.conf.j2, templates/timemaster.conf.j2, tests/tests_ptp_multi.yml
The hybrid_e2e option configures the PTP slave to send delay
requests to the unicast address of the master. This may reduce the
amount of PTP traffic in large networks.
=> Add hybrid_e2e option to PTP domain

tests/tests_ptp_multi.yml, tests/tests_ptp_single.yml
Check the port state in PTP tests to make sure ptp4l is able to initialize the transport and is not blocked by selinux for instance.
=> Check port state in PTP tests

tests/tests_ntp_provider6.yml
I guess earlier versions of Ansible would evaluate this string as
a jinja2 expression when evauluated in a `when` or other conditional
context, but in Ansible 2.12, it gets evaluated as a string.  Ensure
that the evaluation into a boolean happens at variable assignment
time.
=> evaluate is_ntp_default as boolean, not string

tasks/main.yml
When running this role I on a Debian ran into an issue where the ```service_facts``` module reports a bunch of things which have no ```status``` and breaks the subsequent task.
This PR will filter out such ```services```.
=> Fix an issue if a service is listed by service_facts that does not have the 'status' property defined

tasks/main.yml
https://bugzilla.redhat.com/show_bug.cgi?id=2058645
Not sure if it is a problem with rhel9 systemctl list-units, or a problem
with ansible-core 2.12 parsing that output, but service_facts reports
that ptp4l is a valid service, and the service module reports an error
trying to use state: stopped.  For example, here is the corresponding
systemctl status ptp4l when service_facts reports a valid service:
`Failed to get properties: Access denied`
Here is the systemctl list-units output
```
ptp4l.service                          loaded    inactive dead    Precision Time Protocol (PTP) service
```
Here is the service_fact:
```
"ptp4l.service": {
"name": "ptp4l.service",
"source": "systemd",
"state": "stopped",
"status": "inactive"
},
```
The fix is to check the result of the `state: stopped` …
=> handle errors with stopping services

tasks/main.yml, tasks/set_vars.yml, tests/setup-snapshot.yml, tests/tests_default.yml, vars/main.yml
Some users use `gather_facts: false` in their playbooks.  This changes
the role to work in that case, by gathering only the facts it requires
to run.
CI testing can be sped up by creating a snapshot image pre-installed
with packages.  tests/setup-snapshot.yml can be used by a CI system
to do this.
=> support gather_facts: false; support setup-snapshot.yml (#52)

CHANGELOG.md
[1.6.9] - 2022-07-19
- none
- none
- make all tests work with gather_facts: false
Ensure all tests work when using ANSIBLE_GATHERING=explicit
- make min_ansible_version a string in meta/main.yml
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md
=> Version 1.6.9 - CHANGELOG.md [citest skip]

templates/chrony.conf.j2, templates/ntp.conf.j2, templates/phc2sys.sysconfig.j2, templates/ptp4l.conf.j2
Variables are defined as string in Jinja2 template and the operators 
- on line 26 gives '<'  not supported between instances of 'str' and 'float
- on line 43 gives '>' not supported between instances of 'str' and 'float
changed template with type casting.
Had the problem on target RHEL 8.6  en RHEL9.0. In RHEL9.0 setting jinja2_native did work.
Tests done with:
ansible node has ansible 2.9.27/pyhton 3.8.10)
ansible node has ansible 2.9.27/pyhton 3.8.10)
Never had troubles with this system role and very unclear how the vars became strings in Jinja2 templating ..
=> Update chrony.conf.j2 with type casting

CHANGELOG.md
[1.7.0] - 2022-09-19
- adding support fpr Oracle Linux 6,7,8 and 9
- Update chrony.conf.j2
Variables are defined as string in Jinja2 template and the operators
on line 26 gives '<'  not supported between instances of 'str' and 'float
on line 43 gives '>' not supported between instances of 'str' and 'float
- Updated: type casting in overall timesync templates for testing
- Updated: type casting adjusted (timesync_max_distance <= int)
- use ansible_playbook_filepath for ansible-playbook command
=> Version 1.7.0 - CHANGELOG.md [citest skip]

tests/tests_ntp_ptp.yml, tests/tests_ptp_multi.yml, tests/tests_ptp_single.yml
New ethtool versions don't print the upper-case timestamping constants
anymore. Match the lower-case strings instead.
=> Update timestamping checks using ethtool

CHANGELOG.md
[1.7.1] - 2022-11-01
- none
- none
- Update timestamping checks using ethtool
New ethtool versions don't print the upper-case timestamping constants
anymore. Match the lower-case strings instead.
=> Version 1.7.1 - CHANGELOG.md [citest skip]

.github/workflows/woke.yml, CHANGELOG.md, README.md, handlers/main.yml, tasks/main.yml, templates/ptp4l.conf.j2, templates/timemaster.conf.j2, tests/tests_ptp_multi.yml, vars/CentOS_6.yml, vars/CentOS_9.yml, vars/Debian.yml, vars/RedHat_6.yml, vars/RedHat_9.yml, vars/default.yml
Add check for non-inclusive language
Add a check for usage of terms and language that is considered non-inclusive. We are using the woke tool for this with a wordlist that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
Clean up / Workaround non-inclusive words
- CHANGELOG.md
- README.md
- handlers/main.yml
- tasks/main.yml
- templates/ptp4l.conf.j2
- templates/timemaster.conf.j2
- tests/tests_ptp_multi.yml
- vars/CentOS_6.yml
- vars/CentOS_9.yml
- vars/Debian.yml
- vars/RedHat_6.yml
- vars/RedHat_9.yml
- vars/default.yml
Note: woke action depends on https://github.com/linux-system-roles/tox-lsr/pull/103 for skipping the check on the filename timemaster.conf.j2.
=> Add check for non-inclusive language; 

tasks/main.yml
Fix for the following warning:
```
TASK [linux-system-roles.timesync : Disable timemaster] ************************
[WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: '{{ __timemstr }}' in
timesync_services
```
`when`, `that`, and similar are already interpreted as Jinja expressions
and do not require the use of {{ }}
=> Fix jinja formatting issue

templates/chrony.conf.j2, templates/chronyd.sysconfig.j2, templates/ntp.conf.j2, templates/ntpd.sysconfig.j2, templates/phc2sys.sysconfig.j2, templates/ptp4l.conf.j2, templates/ptp4l.sysconfig.j2, templates/timemaster.conf.j2
Add role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.
=> Fingerprint RHEL System Role managed config files

tasks/main.yml, vars/CentOS_6.yml, vars/CentOS_9.yml, vars/Debian.yml, vars/OracleLinux_6.yml, vars/OracleLinux_7.yml, vars/OracleLinux_8.yml, vars/OracleLinux_9.yml, vars/RedHat_6.yml, vars/RedHat_9.yml, vars/default.yml
The config file for chrony is in a different location on Debian (I missed that in #135 :-) )
=> Update chrony.conf location for Debian

vars/AlmaLinux_8.yml, vars/AlmaLinux_9.yml, vars/CentOS_7.yml, vars/CentOS_8.yml, vars/RedHat_7.yml, vars/RedHat_8.yml
Enhancement: Add variables for additional operating systems.
Reason: They are missing, so values in `default.yml` are used.
Result: Everything works as expected in the added operating systems.
The default values are fine for all the operating systems listed, so in my opinion the best approach would be to get rid of all of them, leaving only `default.yml` and simplify. But in the meanwhile, this makes these additional OSes "compliant".
=> refactor: Add CentOS 7-8, RedHat 7-8 and AlmaLinux 8-9 var files

vars/ALP-Dolomite.yml
Enhancement: Add variables for additional operating system.
Reason: The existing configuration does not cover [SUSE ALP](https://documentation.suse.com/alp/dolomite/html/alp-dolomite/index.html), the default configurations are being used.
Result: Works as expected in the added operating system.
Issue Tracker Tickets (Jira or BZ if any):na
=> ci: Add ALP-Dolomite var file

.ansible-lint, .ostree/get_ostree_data.sh, meta/collection-requirements.yml, tasks/main.yml, tasks/set_vars.yml, tests/tasks/setup.yml, tests/tests_ntp_ptp.yml, tests/tests_ptp_multi.yml, tests/tests_ptp_single.yml
The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …
=> refactor: improve support for ostree systems

.github/workflows/ansible-lint.yml, .github/workflows/ansible-managed-var-comment.yml, .github/workflows/ansible-plugin-scan.yml, .github/workflows/ansible-test.yml, .sanity-ansible-ignore-2.17.txt
Upgrade ci tests to use tox-lsr 3.3.0
tox-lsr 3.3.0 uses ansible-test 2.17
Create the ansible-test ignore file for 2.17
=> ci: use tox-lsr 3.3.0 which uses ansible-test 2.17

vars/OracleLinux_8.yml, vars/RedHat_8.yml
On EL8 systems the chrony package uses a helper script which adds servers from DHCP with the "chronyc add" command. The /run/chrony-dhcp directive is used on EL9 and later.
=> fix: Don't use chrony-dhcp sourcedir on EL8 systems

meta/main.yml, vars/AlmaLinux_10.yml, vars/CentOS_10.yml, vars/OracleLinux_10.yml, vars/RedHat_10.yml
According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …
=> fix: add support for EL10

.sanity-ansible-ignore-2.10.txt, .sanity-ansible-ignore-2.11.txt, .sanity-ansible-ignore-2.12.txt, .sanity-ansible-ignore-2.13.txt, .sanity-ansible-ignore-2.14.txt, .sanity-ansible-ignore-2.15.txt, .sanity-ansible-ignore-2.16.txt, .sanity-ansible-ignore-2.17.txt, .sanity-ansible-ignore-2.9.txt, library/timesync_provider.yml
Automation Hub will error and not display module docs for
any module if any of the docs are missing or incorrect.
Since timesync_provider is a shell script, it must have
a separate module doc file.
=> docs: add module documentation for timesync_provider

README.md, defaults/main.yml, tasks/main.yml, tasks/set_vars.yml, vars/SL-Micro.yml
Enhancement: - Added a block to identify and handle reboots for transactional update systems on package changes. Update README. Rename ALP-Dolomite var file to SL-Micro as the name is no longer used.
Reason: Ensure necessary reboots are managed, as changes on transactional update systems are applied in a separate snapshot and require a reboot to take effect.
Result: Manages system reboots for transactional update systems when a package is installed.
Issue Tracker Tickets (Jira or BZ if any):na
=> ci: Handle reboot for transactional update systems

tests/inventory.yaml.j2
Enhancement: Create inventory for wrapper test with inventory_hostname
Reason: Multihost tests have an inventory defining many nodes, then run playbooks with `--limit <node>`. Hence, the role must build inventory for wrapper tests only with the node that it runs against.
Result: Inventory that is created for wrapper tests contains a single node like in https://github.com/linux-system-roles/kdump/blob/main/tests/inventory.yaml.j2
=> ci: Create inventory for wrapper test with inventory_hostname

README.md, defaults/main.yml, templates/chronyd.sysconfig.j2, templates/ntpd.sysconfig.j2, tests/tests_default_vars.yml, tests/tests_options.yml
Feature: Add support for timesync_ntp_ip_family to allow setting the `-4`
or `-6` OPTIONS in the chronyd or ntpd sysconfig file.
Reason: When IPv6 is disabled on the node, you must tell chronyd to
only listen for IPv4 using OPTIONS="-4" in the sysconfig file.
Otherwise, chronyd will log error messages when binding to IPv6 sockets
It's also useful to prevent the client from using IPv6 servers when IPv4
is known to work better (e.g. IPv6 over a tunnel).
Result: chronyd and ntpd can be configured to work correctly, and
the services will not log errors, when IPv6 (or IPv4) is disabled
on the node.
=> feat: add support for timesync_ntp_ip_family

templates/chronyd.sysconfig.j2, vars/Debian.yml, vars/RedHat_10.yml, vars/RedHat_6.yml, vars/RedHat_7.yml, vars/RedHat_8.yml, vars/RedHat_9.yml, vars/SL-Micro.yml, vars/default.yml
Cause: The timesync role is replacing the default `OPTIONS=` setting for chronyd with `""` upon every role run.
Consequence: This removes the default `OPTIONS="-F 2"` setting on EL9 and EL10 which weakens the security of chronyd.
Fix: Add `-F 2` as the default setting for `OPTIONS` in EL9 and EL10.  Ensure that the user can override this setting if necessary, and ensure that this setting can co-exist with other `OPTIONS` settings that may be set by the user.
Result: The timesync role applies the correct security settings on every platform and allows the user to override/extend these settings.
Fixes #278
=> fix: add default seccomp filters for el9/10

vars/OracleLinux_10.yml, vars/OracleLinux_6.yml, vars/OracleLinux_7.yml, vars/OracleLinux_8.yml, vars/OracleLinux_9.yml
The OracleLinux vars files were out of sync with the other EL vars.
There is no reason for this, they should be exactly the same.
Make the OracleLinux vars files symlinks to the RedHat vars files,
like the other EL vars files.
Fixes https://github.com/linux-system-roles/timesync/issues/282
=> refactor: make OracleLinux vars files symlinks to RedHat vars files

tests/tests_options.yml, vars/Fedora.yml
Add a test to ensure that running the role with no
variables does not remove the default OPTIONS for seccomp.
This also required adding a vars file for Fedora
=> test: add test for secccomp on el9/el10

.github/workflows/ansible-lint.yml, .github/workflows/ansible-managed-var-comment.yml, .github/workflows/ansible-test.yml, .github/workflows/qemu-kvm-integration-tests.yml
Use tox-lsr 3.12.0 for the new osbuild_config.yml feature for bootc and users
https://github.com/linux-system-roles/tox-lsr/pull/211
=> ci: use tox-lsr 3.12.0 for osbuild_config.yml feature
