README.md
library/timesync_provider.sh
tasks/main.yml
tests/tests_ntp_clean.yml
vars/main.yml

Move the default selection to vars/main.yml and the decision algorithm to tasks/main.yml

---

examples/multiple-ntp-servers.yml
examples/single-pool.yml

Updated examples from https://git.centos.org/tree/rpms!rhel-system-roles.git/c7-extras/SOURCES

Add example playbooks

---

.travis.yml
README.md
molecule/default/Dockerfile.j2
molecule/default/molecule.yml
molecule/default/yamllint.yml

Configures Molecule to do basic checks (lint/syntax, run, idempotence, Ansible check mode functionality) of the role with default parameters (tests/tests_default.yml) using Travis CI and centos6/7 docker containers.

Configure Molecule and Travis CI (this PR should trigger build in CI)

---

tests/inventory.yaml.j2
tests/tests_default_wrapper.yml

Add a playbook that works as a wrapper that runs tests of role
with default values of role variables both in normal and in
check mode.

Run tests_default both in normal and in check mode

---

tests/tests_default_vars.yml

Add test that checks the role defines all its parameters in defaults.

Add default vars test

---

tasks/main.yml
templates/chrony.conf.j2
templates/ntp.conf.j2
templates/timemaster.conf.j2
tests/tests_ntp.yml
tests/tests_ntp_provider1.yml
tests/tests_ntp_provider2.yml
tests/tests_ntp_provider3.yml
tests/tests_ntp_provider4.yml
tests/tests_ntp_provider5.yml
tests/tests_ntp_provider6.yml
tests/tests_ntp_ptp.yml
tests/tests_ptp_multi.yml
tests/tests_ptp_single.yml
vars/main.yml

Fix the role if executed in check mode without having been executed in normal mode before.
https://github.com/linux-system-roles/timesync/issues/51

Fix check mode

---

.travis.yml
.travis/config.sh
.travis/custom.sh
.travis/runblack.sh
.travis/runcoveralls.sh
.travis/runflake8.sh
.travis/runpylint.sh
.travis/runpytest.sh
.travis/runshellcheck.sh
.travis/runsyspycmd.sh
.travis/utils.sh
.yamllint_defaults.yml
library/timesync_provider.sh
tests/setup_module_utils.sh
tox.ini

sync with latest template including shellcheck
fix shellcheck issues

sync with latest template including shellcheck

---

.travis/runcollection.sh
.travis/utils.sh
tox.ini

- Adding .travis/runcollection.sh.
- Enabling collection as part of tox/travis tests.

RHELPLAN-56589 - sync collections related changes from template to timesync role

---

README.md
templates/chrony.conf.j2
tests/tests_chrony.yml

Added custom settings for ```chrony.conf```

add timesync_chrony_custom_settings variable for free-form local configs

---

tests/tests_default_wrapper.yml

Tag some tests that are slow, to skip for fast basic smoke testing

tag tests with slow

---

.github/workflows/tox.yml
.sanity-ansible-ignore-2.12.txt

support python 39, ansible-core 2.12, ansible-plugin-scan

support python 39, ansible-core 2.12, ansible-plugin-scan

---

tasks/main.yml

see also https://github.com/linux-system-roles/storage/pull/238

also reject masked and failed services

---

tasks/main.yml
vars/CentOS_6.yml
vars/CentOS_9.yml
vars/Debian.yml
vars/Fedora_33.yml
vars/RedHat_6.yml
vars/RedHat_9.yml
vars/default.yml

With these edits (and the one from #134 ) I was able to succesfully configure Chronyd on my Debian system.
Feedback is appreciated! :-)

Initial version for Debian

---

CHANGELOG.md

[1.7.2] - 2023-01-20
- none
- fixes for ansible-lint 6.x
- ensure ethtool is installed where needed
- Add check for non-inclusive language;  (#170)
- Clean up / Workaround non-inclusive words
- update ignore files for ansible-test 2.14 (#172)

Version 1.7.2 - CHANGELOG.md [citest skip]

---

CHANGELOG.md

[1.7.3] - 2023-04-06
- Update chrony.conf location for Debian (#187)
- suppress shellcheck issue (#176)
- Fix jinja formatting issue (#178)
- Add README-ansible.md to refer Ansible intro page on linux-system-roles.github.io (#185)
- Fingerprint RHEL System Role managed config files (#186)

Version 1.7.3 - CHANGELOG.md [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.7.5

docs(changelog): version 1.7.5 [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.7.6

docs(changelog): version 1.7.6 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.7.7

docs(changelog): version 1.7.7 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.7.8

docs(changelog): version 1.7.8 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.7.9

docs(changelog): version 1.7.9 [citest skip]

---

.ansible-lint
.markdownlint.yaml
.sanity-ansible-ignore-2.16.txt

Fix yamllint issue with markdownlint config

ci: support ansible-lint and ansible-test 2.16

---

CHANGELOG.md

Update changelog and .README.html for version 1.8.3
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

docs(changelog): version 1.8.3 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.8.4

docs(changelog): version 1.8.4 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.8.5

docs(changelog): version 1.8.5 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.8.6

docs(changelog): version 1.8.6 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.9.1

docs(changelog): version 1.9.1 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.9.2

docs(changelog): version 1.9.2 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.10.0

docs(changelog): version 1.10.0 [citest skip]
